package codigo;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Blanca
 */
public class VentanaCalculadora2 extends javax.swing.JFrame {

    double operando1 = 0; //guarda el primer número que metamos
    String operacion = ""; //guarda la operación pulsada

    /**
     * Creates new form VentanaCalculadora
     */
    public VentanaCalculadora2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantalla = new javax.swing.JLabel();
        boton07 = new javax.swing.JButton();
        boton08 = new javax.swing.JButton();
        boton09 = new javax.swing.JButton();
        boton05 = new javax.swing.JButton();
        boton06 = new javax.swing.JButton();
        boton04 = new javax.swing.JButton();
        boton01 = new javax.swing.JButton();
        boton02 = new javax.swing.JButton();
        boton03 = new javax.swing.JButton();
        boton00 = new javax.swing.JButton();
        BotonSuma = new javax.swing.JButton();
        BotonResta = new javax.swing.JButton();
        BotonIgual = new javax.swing.JButton();
        BotonMultiplicacion = new javax.swing.JButton();
        BotonDivision = new javax.swing.JButton();
        BotonAC = new javax.swing.JButton();
        BotonComa = new javax.swing.JButton();
        BotonNegPos = new javax.swing.JButton();
        Título = new javax.swing.JTextField();
        BotonPorcentaje = new javax.swing.JButton();
        BotonEasterEgg = new javax.swing.JButton();
        BotonRaizCuadrada = new javax.swing.JButton();
        BotonAlCuadrado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pantalla.setBackground(new java.awt.Color(0, 0, 0));
        pantalla.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        pantalla.setForeground(new java.awt.Color(51, 255, 51));
        pantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pantalla.setText("0");
        pantalla.setOpaque(true);
        getContentPane().add(pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 386, 56));

        boton07.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton07.setText("7");
        boton07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton07ActionPerformed(evt);
            }
        });
        getContentPane().add(boton07, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 60, 81));

        boton08.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton08.setText("8");
        boton08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton08ActionPerformed(evt);
            }
        });
        getContentPane().add(boton08, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 60, 81));

        boton09.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton09.setText("9");
        boton09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton09ActionPerformed(evt);
            }
        });
        getContentPane().add(boton09, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 60, 81));

        boton05.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton05.setText("5");
        boton05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton05ActionPerformed(evt);
            }
        });
        getContentPane().add(boton05, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 60, 81));

        boton06.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton06.setText("6");
        boton06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton06ActionPerformed(evt);
            }
        });
        getContentPane().add(boton06, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 60, 81));

        boton04.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton04.setText("4");
        boton04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton04ActionPerformed(evt);
            }
        });
        getContentPane().add(boton04, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 60, 81));

        boton01.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton01.setText("1");
        boton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton01ActionPerformed(evt);
            }
        });
        getContentPane().add(boton01, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 60, 81));

        boton02.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton02.setText("2");
        boton02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton02ActionPerformed(evt);
            }
        });
        getContentPane().add(boton02, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 60, 81));

        boton03.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton03.setText("3");
        boton03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton03ActionPerformed(evt);
            }
        });
        getContentPane().add(boton03, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 60, 81));

        boton00.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton00.setText("0");
        boton00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton00ActionPerformed(evt);
            }
        });
        getContentPane().add(boton00, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 60, 81));

        BotonSuma.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonSuma.setText("+");
        BotonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSumaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 63, -1));

        BotonResta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonResta.setText("-");
        BotonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRestaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 63, -1));

        BotonIgual.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonIgual.setText("=");
        BotonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIgualActionPerformed(evt);
            }
        });
        getContentPane().add(BotonIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 63, -1));

        BotonMultiplicacion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonMultiplicacion.setText("×");
        BotonMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMultiplicacionActionPerformed(evt);
            }
        });
        getContentPane().add(BotonMultiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 63, -1));

        BotonDivision.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonDivision.setText("÷");
        BotonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDivisionActionPerformed(evt);
            }
        });
        getContentPane().add(BotonDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 63, -1));

        BotonAC.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonAC.setText("AC");
        BotonAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonACActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 63, -1));

        BotonComa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonComa.setText(",");
        BotonComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonComaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonComa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 63, -1));

        BotonNegPos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonNegPos.setText("+/-");
        BotonNegPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNegPosActionPerformed(evt);
            }
        });
        getContentPane().add(BotonNegPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        Título.setBackground(new java.awt.Color(255, 51, 51));
        Título.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        Título.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Título.setText("CALCULADORA BLANCA");
        Título.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TítuloActionPerformed(evt);
            }
        });
        getContentPane().add(Título, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 300, 40));

        BotonPorcentaje.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonPorcentaje.setText("%");
        BotonPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPorcentajeActionPerformed(evt);
            }
        });
        getContentPane().add(BotonPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 63, -1));

        BotonEasterEgg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonEasterEgg.setText("EASTER EGG");
        BotonEasterEgg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEasterEggActionPerformed(evt);
            }
        });
        getContentPane().add(BotonEasterEgg, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, -1));

        BotonRaizCuadrada.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonRaizCuadrada.setText("√");
        BotonRaizCuadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRaizCuadradaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonRaizCuadrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 60, -1));

        BotonAlCuadrado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonAlCuadrado.setText("^2");
        BotonAlCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAlCuadradoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAlCuadrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton07ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar.equals("0")) {
            pantalla.setText("7");
        } else {
            pantalla.setText(auxiliar + "7");
        }
    }//GEN-LAST:event_boton07ActionPerformed

    private void boton08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton08ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar.equals("0")) {
            pantalla.setText("8");
        } else {
            pantalla.setText(auxiliar + "8");
        }
    }//GEN-LAST:event_boton08ActionPerformed

    private void boton09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton09ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar.equals("0")) {
            pantalla.setText("9");
        } else {
            pantalla.setText(auxiliar + "9");
        }
    }//GEN-LAST:event_boton09ActionPerformed

    private void boton04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton04ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar.equals("0")) {
            pantalla.setText("4");
        } else {
            pantalla.setText(auxiliar + "4");
        }
    }//GEN-LAST:event_boton04ActionPerformed

    private void boton05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton05ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar.equals("0")) {
            pantalla.setText("5");
        } else {
            pantalla.setText(auxiliar + "5");
        }
    }//GEN-LAST:event_boton05ActionPerformed

    private void boton06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton06ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar.equals("0")) {
            pantalla.setText("6");
        } else {
            pantalla.setText(auxiliar + "6");
        }
    }//GEN-LAST:event_boton06ActionPerformed

    private void boton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton01ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar.equals("0")) {
            pantalla.setText("1");
        } else {
            pantalla.setText(auxiliar + "1");
        }
    }//GEN-LAST:event_boton01ActionPerformed

    private void boton02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton02ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar.equals("0")) {
            pantalla.setText("2");
        } else {
            pantalla.setText(auxiliar + "2");
        }
    }//GEN-LAST:event_boton02ActionPerformed

    private void boton03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton03ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar.equals("0")) {
            pantalla.setText("3");
        } else {
            pantalla.setText(auxiliar + "3");
        }
    }//GEN-LAST:event_boton03ActionPerformed

    private void boton00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton00ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar.equals("0")) {
            pantalla.setText("0");
        } else {
            pantalla.setText(auxiliar + "0");
        }
    }//GEN-LAST:event_boton00ActionPerformed

    private void BotonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSumaActionPerformed
        operacion = "+";
        operando1 = Double.valueOf(pantalla.getText());
        pantalla.setText("0");
    }//GEN-LAST:event_BotonSumaActionPerformed

    private void BotonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRestaActionPerformed
        operacion = "-";
        operando1 = Double.valueOf(pantalla.getText());
        pantalla.setText("0");
    }//GEN-LAST:event_BotonRestaActionPerformed

    private void BotonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIgualActionPerformed
        double operando2 = Double.valueOf(pantalla.getText());
        if (operacion.equals("+")) {
            operando1 = operando1 + operando2;
        }
        if (operacion.equals("-")) {
            operando1 = operando1 - operando2;
        }
        if (operacion.equals("*")) {
            operando1 = operando1 * operando2;
        }
        if (operacion.equals("/")) {
            operando1 = operando1 / operando2;
        }
        if (operacion.equals("%")) {
            operando1 = (operando1 / 100) * operando2;
        }
        if (operacion.equals("√")) {
            operando1 = Math.sqrt(operando1);
        }
        if (operacion.equals("^2")) {
            operando1 = Math.pow(operando1, 2);
        }
        pantalla.setText("" + operando1);
    }//GEN-LAST:event_BotonIgualActionPerformed

    private void BotonMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMultiplicacionActionPerformed
        operacion = "*";
        operando1 = Double.valueOf(pantalla.getText());
        pantalla.setText("0");
    }//GEN-LAST:event_BotonMultiplicacionActionPerformed

    private void BotonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDivisionActionPerformed
        operacion = "/";
        operando1 = Double.valueOf(pantalla.getText());
        pantalla.setText("0");
    }//GEN-LAST:event_BotonDivisionActionPerformed

    private void BotonACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonACActionPerformed
        //BOTÓN DEL AC
        pantalla.setText("0");
    }//GEN-LAST:event_BotonACActionPerformed

    private void BotonComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonComaActionPerformed
        //BOTÓN DE LA COMA
        if (!(pantalla.getText().contains("."))) {
            pantalla.setText(pantalla.getText() + ".");
        }
        if (pantalla.getText().contains(".")) {
            pantalla.setText(pantalla.getText());
        }
    }//GEN-LAST:event_BotonComaActionPerformed

    private void BotonNegPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNegPosActionPerformed
        Double número;
        String pantalla1;
        pantalla1 = pantalla.getText();
        número = (-1) * Double.valueOf(pantalla1);
        pantalla.setText(número.toString());
    }//GEN-LAST:event_BotonNegPosActionPerformed

    private void BotonPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPorcentajeActionPerformed
//BOTÓN PORCENTAJE
        operacion = "%";
        operando1 = Double.valueOf(pantalla.getText());
        pantalla.setText("0");
    }//GEN-LAST:event_BotonPorcentajeActionPerformed

    private void TítuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TítuloActionPerformed
    }//GEN-LAST:event_TítuloActionPerformed

    private void BotonEasterEggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEasterEggActionPerformed
        String jorge;
        jorge = "JORGE ES EL MEJOR <3";
        pantalla.setText(jorge);

    }//GEN-LAST:event_BotonEasterEggActionPerformed

    private void BotonRaizCuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRaizCuadradaActionPerformed
        operacion = "√";
        operando1 = Double.valueOf(pantalla.getText());
    }//GEN-LAST:event_BotonRaizCuadradaActionPerformed

    private void BotonAlCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAlCuadradoActionPerformed
        operacion = "^2";
        operando1 = Double.valueOf(pantalla.getText());
    }//GEN-LAST:event_BotonAlCuadradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCalculadora2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAC;
    private javax.swing.JButton BotonAlCuadrado;
    private javax.swing.JButton BotonComa;
    private javax.swing.JButton BotonDivision;
    private javax.swing.JButton BotonEasterEgg;
    private javax.swing.JButton BotonIgual;
    private javax.swing.JButton BotonMultiplicacion;
    private javax.swing.JButton BotonNegPos;
    private javax.swing.JButton BotonPorcentaje;
    private javax.swing.JButton BotonRaizCuadrada;
    private javax.swing.JButton BotonResta;
    private javax.swing.JButton BotonSuma;
    private javax.swing.JTextField Título;
    private javax.swing.JButton boton00;
    private javax.swing.JButton boton01;
    private javax.swing.JButton boton02;
    private javax.swing.JButton boton03;
    private javax.swing.JButton boton04;
    private javax.swing.JButton boton05;
    private javax.swing.JButton boton06;
    private javax.swing.JButton boton07;
    private javax.swing.JButton boton08;
    private javax.swing.JButton boton09;
    private javax.swing.JLabel pantalla;
    // End of variables declaration//GEN-END:variables
}
